[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "macanalog_symbolix"
description = "Symbolic toolbox to analyze analog circuits"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    'pytest >= 8.2.2',
    'sympy >=1.13.3',
    'tqdm >= 4.67.1'
]


[project.scripts]
run-symbolix = "macanalog_symbolix:main"